import b1 from '../src/assets/b1.jpeg';
import b2 from '../src/assets/b2.jpeg';
import b3 from '../src/assets/b3.jpeg';
import b4 from '../src/assets/b4.jpeg';
import c1 from '../src/assets/c1.jpeg';
import c2 from '../src/assets/c2.jpeg';
import c3 from '../src/assets/c3.jpeg';
import c4 from '../src/assets/c4.jpeg';
import g1 from '../src/assets/g1.jpeg';
import g2 from '../src/assets/g2.jpeg';
import g3 from '../src/assets/g3.jpeg';
import g4 from '../src/assets/g4.jpeg';

let all_products = [
  {
    id: 1,
    name: 'Lorem Ipsum es simplemente el texto',
    image: b1,
    image1: b1,
    image2: b1,
    image3: b2,
    image4: b2,
    new_price: 15000,
    old_price: 20000,
    category: 'Boys',
    tag: 'Boys, Fashion, Kids',
    description:
      ' Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
    prices: {
      S: 15000,
      M: 18000,
      L: 20000,
      XL: 22000,
      XXL: 25000,
    },
  },
  {
    id: 2,
    name: 'Lorem Ipsum es simplemente el texto',
    image: b2,
    image1: b2,
    image2: b2,
    image3: b3,
    image4: b3,
    new_price: 15000,
    old_price: 20000,
    category: 'Boys',
    tag: 'Boys, Fashion, Kids',
    description:
      ' Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
    prices: {
      S: 15000,
      M: 18000,
      L: 20000,
      XL: 22000,
      XXL: 25000,
    },
  },
  {
    id: 3,
    name: 'Lorem Ipsum es simplemente el texto',
    image: b3,
    image1: b3,
    image2: b3,
    image3: b4,
    image4: b4,
    new_price: 15000,
    old_price: 20000,
    category: 'Boys',
    tag: 'Boys, Fashion, Kids',
    description:
      ' Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
    prices: {
      S: 15000,
      M: 18000,
      L: 20000,
      XL: 22000,
      XXL: 25000,
    },
  },
  {
    id: 4,
    name: 'Lorem Ipsum es simplemente el texto',
    image: b4,
    image1: b4,
    image2: b4,
    image3: b4,
    image4: b4,
    new_price: 15000,
    old_price: 20000,
    category: 'Boys',
    tag: 'Boys, Fashion, Kids',
    description:
      ' Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
    prices: {
      S: 15000,
      M: 18000,
      L: 20000,
      XL: 22000,
      XXL: 25000,
    },
  },
  {
    id: 5,
    name: 'Lorem Ipsum es simplemente el texto',
    image: c1,
    image1: c1,
    image2: c2,
    image3: c2,
    image4: c2,
    new_price: 15000,
    old_price: 20000,
    category: 'Casuals',
    tag: 'Casuals, Fashion, Kids',
    description:
      ' Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
    prices: {
      S: 15000,
      M: 18000,
      L: 20000,
      XL: 22000,
      XXL: 25000,
    },
  },
  {
    id: 6,
    name: 'Lorem Ipsum es simplemente el texto',
    image: c2,
    image1: c2,
    image2: c2,
    image3: c3,
    image4: c3,
    new_price: 15000,
    old_price: 20000,
    category: 'Casuals',
    tag: 'Casuals, Fashion, Kids',
    description:
      ' Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
    prices: {
      S: 15000,
      M: 18000,
      L: 20000,
      XL: 22000,
      XXL: 25000,
    },
  },
  {
    id: 7,
    name: 'Lorem Ipsum es simplemente el texto',
    image: c3,
    image1: c3,
    image2: c3,
    image3: c4,
    image4: c4,
    new_price: 15000,
    old_price: 20000,
    category: 'Casuals',
    tag: 'Casuals, Fashion, Kids',
    description:
      ' Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
    prices: {
      S: 15000,
      M: 18000,
      L: 20000,
      XL: 22000,
      XXL: 25000,
    },
  },
  {
    id: 8,
    name: 'Lorem Ipsum es simplemente el texto',
    image: c4,
    image1: c4,
    image2: c4,
    image3: c4,
    image4: c4,
    new_price: 15000,
    old_price: 20000,
    category: 'Casuals',
    tag: 'Casuals, Fashion, Kids',
    description:
      ' Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
    prices: {
      S: 15000,
      M: 18000,
      L: 20000,
      XL: 22000,
      XXL: 25000,
    },
  },
  {
    id: 9,
    name: 'Lorem Ipsum es simplemente el texto',
    image: g1,
    image1: g1,
    image2: g1,
    image3: g2,
    image4: g2,
    new_price: 15000,
    old_price: 20000,
    category: 'Girls',
    tag: 'Girls, Fashion, Kids',
    description:
      ' Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
    prices: {
      S: 15000,
      M: 18000,
      L: 20000,
      XL: 22000,
      XXL: 25000,
    },
  },
  {
    id: 10,
    name: 'Lorem Ipsum es simplemente el texto',
    image: g2,
    image1: g2,
    image2: g2,
    image3: g3,
    image4: g3,
    new_price: 15000,
    old_price: 20000,
    category: 'Girls',
    tag: 'Girls, Fashion, Kids',
    description:
      ' Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
    prices: {
      S: 15000,
      M: 18000,
      L: 20000,
      XL: 22000,
      XXL: 25000,
    },
  },
  {
    id: 11,
    name: 'Lorem Ipsum es simplemente el texto',
    image: g3,
    image1: g3,
    image2: g3,
    image3: g4,
    image4: g4,
    new_price: 15000,
    old_price: 20000,
    category: 'Girls',
    tag: 'Girls, Fashion, Kids',
    description:
      ' Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
    prices: {
      S: 15000,
      M: 18000,
      L: 20000,
      XL: 22000,
      XXL: 25000,
    },
  },
  {
    id: 12,
    name: 'Lorem Ipsum es simplemente el texto',
    image: g4,
    image1: g4,
    image2: g4,
    image3: g4,
    image4: g4,
    new_price: 15000,
    old_price: 20000,
    category: 'Girls',
    tag: 'Girls, Fashion, Kids',
    description:
      ' Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen.',
    prices: {
      S: 15000,
      M: 18000,
      L: 20000,
      XL: 22000,
      XXL: 25000,
    },
  },
];

export default all_products;
